ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('order.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
]

order/urls.py
from django.urls import path, include
from .views import ItemListView, ItemDetailView, add_to_cart, remove_from_cart, order_summary, delete_from_summary, \
    checkout, add_new_address, select_from_saved_addresses, payment_process, payment_done, payment_canceled, \
    PortfolioCreateView, ProductCreateView, PortfolioListView, PortfolioDetailView, contact_us_view

urlpatterns = [
    path('', ItemListView.as_view(), name='item-list'),
    path('portfolios/', PortfolioListView.as_view(), name='portfolio-list'),
    path('product/<slug:slug>', ItemDetailView.as_view(), name='item-detail'),
    path('portfolio/<int:pk>', PortfolioDetailView.as_view(), name='portfolio-detail'),
    path('add-to-cart/<slug:slug>', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug:slug>', remove_from_cart, name='remove-from-cart'),
    path('delete-from-summary/<slug:slug>', delete_from_summary, name='delete-from-summary'),
    path('order-summary', order_summary, name='order-summary'),
    path('check-out', checkout, name='check-out'),
    path('add-new-address', add_new_address, name='add-new-address'),
    path('select-from-saved-addresses/', select_from_saved_addresses, name='select-from-saved-addresses'),
    path('process-payment/<int:order_id>', payment_process, name='process_payment'),
    path('payment-done/', payment_done, name='payment_done'),
    path('payment-cancelled/', payment_canceled, name='payment_cancelled'),
    path('add-portfolio/', PortfolioCreateView.as_view(), name='add-portfolio'),
    path('add-product/', ProductCreateView.as_view(), name='add-product'),
    path('contact-form/', contact_us_view, name='contact-form'),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (('S', 'Shirt'), ('SW', 'Sports Wear'), ('OW', 'Out Wear'))
LABEL_CHOICES = (('P', 'primary'), ('S', 'secondary'), ('D', 'danger'))


class Item(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2, default='S')
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, default='P')
    slug = models.SlugField()
    vendor = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('item-detail', kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse('add-to-cart', kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse('remove-from-cart', kwargs={'slug': self.slug})

    def get_delete_from_summary_url(self):
        return reverse('delete-from-summary', kwargs={'slug': self.slug})


class BillingAddress(models.Model):
    address = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100, blank=True, null=True)
    country = CountryField(blank_label='(select country)')
    zip = models.CharField(max_length=10)
    default_address = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.OneToOneField(BillingAddress, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.user.username

    def get_total_price(self):
        total_price = 0
        for order_item in self.orderitem_set.all():
            total_price += order_item.get_cost()
        return total_price

    def get_order_payment_url(self):
        return reverse('process_payment', kwargs={'order_id': self.id})


class OrderItem(models.Model):
    item = models.OneToOneField(Item, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField(default=1)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __str__(self):
        return self.item.title

    def get_cost(self):
        return self.item.price * self.quantity


class Coupon(models.Model):
    code = models.CharField(max_length=10)
    expiry_date = models.DateTimeField(blank=True, null=True)
    discount = models.IntegerField()


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_vendor = models.BooleanField(default=False)


class Portfolio(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    about = models.TextField()
    email = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=15)
    picture = models.ImageField()

    def get_absolute_url(self):
        return reverse('portfolio-detail', kwargs={'pk': self.pk})

order/forms.py
from django import forms
from order.models import BillingAddress, Coupon, Portfolio
from phonenumber_field.formfields import PhoneNumberField


class BillingAddressForm(forms.ModelForm):

    class Meta:
        model = BillingAddress
        fields = ('address', 'address2', 'country', 'zip', 'default_address')
        widgets = {
            'address': forms.TextInput(attrs={'placeholder': '1234 Main St'}),
            'address2': forms.TextInput(attrs={'placeholder': 'Apartment or suite'}),
        }
        labels = {
            'address2': 'address2(optional)',
            'default_address': 'Make this your default address'
        }


class PortfolioForm(forms.ModelForm):

    class Meta:
        model = Portfolio
        fields = ('about', 'email', 'phone_number', 'picture')


class CouponForm(forms.Form):

    class Meta:
        fields = ('code',)
        labels = {
            'code': 'coupon code',
        }
        widgets = {
            'code': forms.TextInput(attrs={'placeholder': "Promo code"})
        }


class ContactForm(forms.Form):
    First_Name = forms.CharField()
    Last_Name = forms.CharField()
    Email = forms.EmailField()
    Phone_Number = PhoneNumberField()

order/views.py
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect, redirect, reverse
from django.views.generic import ListView, DetailView
from .models import Item, OrderItem, Order, BillingAddress, Portfolio
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import BillingAddressForm, CouponForm, ContactForm
from django.conf import settings
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


class ItemListView(ListView):
    model = Item
    template_name = 'order/home-page.html'
    context_object_name = 'items'


class PortfolioListView(ListView):
    model = Portfolio
    template_name = 'order/portfolio-page.html'
    context_object_name = 'items'


class ItemDetailView(DetailView):
    model = Item
    template_name = 'order/product-page.html'
    context_object_name = 'item'


class PortfolioDetailView(DetailView):
    model = Portfolio
    template_name = 'order/portfolio-detail-page.html'
    context_object_name = 'item'


def httpresponseredirectlogin(url):
    if 'accounts/login' in url:
        return redirect('/')
    else:
        return HttpResponseRedirect(url)


@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user).filter(ordered=False)
    if order_qs.exists():
        order = order_qs.first()
        order_item_qs = OrderItem.objects.filter(order=order).filter(item=item)
        if order_item_qs.exists():
            order_item = order_item_qs.first()
            order_item.quantity += 1
            order_item.save()
        else:
            OrderItem.objects.create(item=item, order=order)
    else:
        order = Order.objects.create(user=request.user, ordered_date=timezone.now())
        OrderItem.objects.create(item=item, order=order)
    messages.success(request, 'This item has been added to your cart')
    return httpresponseredirectlogin(request.META.get('HTTP_REFERER'))


@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user).filter(ordered=False)
    if order_qs.exists():
        order = order_qs.first()
        order_item_qs = OrderItem.objects.filter(order=order).filter(item=item)
        if order_item_qs.exists():
            order_item = order_item_qs.first()
            if order_item.quantity > 1:
                order_item.quantity = order_item.quantity - 1
                order_item.save()
            else:
                order_item.delete()
            messages.success(request, 'This item has been removed from your cart')
        else:
            # send message order doesn't contain item
            messages.success(request, 'Your cart does not contain this item')
    else:
        # send message order doesn't exist
        messages.success(request, 'Your cart does not contain this item')
    return httpresponseredirectlogin(request.META.get('HTTP_REFERER'))


@login_required
def order_summary(request):
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs.first()
        return render(request, 'order/order_summary.html', {'order': order})
    messages.success(request, 'Please add items to cart')
    return httpresponseredirectlogin(request.META.get('HTTP_REFERER'))


@login_required
def delete_from_summary(request, slug):
    item = get_object_or_404(Item, slug=slug)
    order_qs = Order.objects.filter(user=request.user).filter(ordered=False)
    if order_qs.exists():
        order = order_qs.first()
        order_item_qs = OrderItem.objects.filter(order=order).filter(item=item)
        if order_item_qs.exists():
            order_item = order_item_qs.first()
            order_item.delete()
            messages.success(request, 'This item has been removed from your cart')
        else:
            # send message order doesn't contain item
            messages.success(request, 'Your cart does not contain this item')
    else:
        # send message order doesn't exist
        messages.success(request, 'Your cart does not contain this item')
    return httpresponseredirectlogin(request.META.get('HTTP_REFERER'))


@login_required
def checkout(request):
    if request.method == 'POST':
        form = CouponForm(data=request.POST)
        if form.is_valid():

            form.save()
    context = {}
    order_qs = Order.objects.filter(user=request.user).filter(ordered=False)
    order = order_qs.first()
    context['order'] = order
    saved_addresses_qs = request.user.billingaddress_set.all()
    if saved_addresses_qs.exists():
        context['saved_addresses'] = saved_addresses_qs
        default_address_qs = request.user.billingaddress_set.filter(default_address=True)
        if default_address_qs.exists():
            default_address = default_address_qs.first()
            context['default_address'] = default_address
    return render(request, 'order/checkout-page.html', context=context)


@login_required
def add_new_address(request):
    if request.method == 'POST':
        order_qs = Order.objects.filter(user=request.user).filter(ordered=False)
        order = order_qs.first()
        form = BillingAddressForm(data=request.POST)
        if form.is_valid():
            form.instance.user = request.user
            if form.cleaned_data.get('default_address'):
                billing_address_qs = request.user.billingaddress_set.filter(default_address=True)
                if billing_address_qs.exists():
                    billing_address = billing_address_qs.first()
                    billing_address.default_address = False
            form.save()
            order.billing_address = form.instance
            order.save()
            return redirect(reverse('process_payment', kwargs={'order_id': order.id}))
        else:
            print(form.errors)
    form = BillingAddressForm()
    return render(request, 'order/add-new-address.html', {'form': form})


@login_required
def select_from_saved_addresses(request):
    if request.GET.get('billing_id'):
        billing_id = request.GET.get('billing_id')
        billing_address = get_object_or_404(BillingAddress, id=int(billing_id))
        order_qs = Order.objects.filter(user=request.user).filter(ordered=False)
        order = order_qs.first()
        order.billing_address = billing_address
        order.save()
        order_id = order.id
        return redirect(reverse('process_payment', kwargs={'order_id': order_id}))
    saved_addresses_qs = request.user.billingaddress_set.all()
    return render(request, 'order/select-from-saved-addresses.html', {'saved_addresses': saved_addresses_qs})


@login_required
def payment_process(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    host = request.get_host()
    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': order.get_total_price(),
        'item_name': 'Order {}'.format(order.id),
        'invoice': str(order.id),
        'currency_code': 'INR',
        'notify_url': 'http://{}{}'.format(host,
                                           reverse('paypal-ipn')),
        'return_url': 'http://{}{}'.format(host,
                                           reverse('payment_done')),
        'cancel_return': 'http://{}{}'.format(host,
                                              reverse('payment_cancelled')),
    }

    form = PayPalPaymentsForm(initial=paypal_dict)
    return render(request, 'order/process_payment.html', {'order': order, 'form': form})


@csrf_exempt
def payment_done(request):
    return render(request, 'order/payment_done.html')


@csrf_exempt
def payment_canceled(request):
    return render(request, 'order/payment_cancelled.html')


class PortfolioCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Portfolio
    fields = ['about', 'email', 'phone_number', 'picture']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.profile.is_vendor:
            return True
        return False


class ProductCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Item
    fields = ['title', 'description', 'price']

    def form_valid(self, form):
        form.instance.vendor = self.request.user
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.profile.is_vendor:
            return True
        return False


def contact_us_view(request):
    if request.method == 'POST':
        contact_form = ContactForm(data=request.POST)
        if contact_form.is_valid():
            print(contact_form.cleaned_data)
            mail_content = "Hello, This is a simple mail. There is only text, " \
                           "no attachments are there The mail is sent using Python SMTP library. Thank You"
            # The mail addresses and password
            sender_address = 'harish.gunda16@gmail.com'
            sender_pass = 'baqtfqchkuxzviwo'
            receiver_address = 'harish.gunda16@gmail.com'
            # Setup the MIME
            message = MIMEMultipart()
            message['From'] = sender_address
            message['To'] = receiver_address
            message['Subject'] = 'A test mail sent by Python. It has an attachment.'   # The subject line
            # The body and the attachments for the mail
            message.attach(MIMEText(mail_content, 'plain'))
            # Create SMTP session for sending the mail

order/templates/order/add-new-address.html
{% extends "order/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <!--Main layout-->
  <main>
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
            <!--Card-->
              <!--Card content-->
          <div class="card">
          <form class="card-body" method="POST">

          <!--Grid row-->
            <div class="row">
            <!--Grid column-->
              <div class="col-md-8 mb-2">
              <!--Card content-->
                {% csrf_token %}
                <fieldset class="">
                  <legend class="border-bottom mb-4">Add new address</legend>
                  {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                  <button class="btn btn-primary" type="submit">Deliver to this address</button>
                </div>
              </div>
            </div>
          </form>
          </div>


        </div>



        <!--Grid column-->
        <div class="col-md-4 mb-4">



        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

order/templates/order/checkout-page.html
{% extends "order/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <!--Main layout-->
  <main>
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
            <!--Card-->
           {% if default_address %}
              <div class="ml-2">
                <h4>Your Default Address</h4>
                <p><b>address:</b> {{ default_address.address }}</p>
                <p><b>address2:</b> {{ default_address.address2 }}</p>
                <p><b>country:</b> {{ default_address.country.name }}</p>
                <p><b>zip:</b> {{ default_address.zip }}</p>
              </div>
              <a class="btn btn-primary" href="{{ order.get_order_payment_url }}">Deliver to default address</a>
              <a class="btn btn-info float-right" href="{% url 'add-new-address' %}">Add new address</a>
            {% else %}
              <a class="btn btn-info" href="{% url 'add-new-address' %}">Add new address</a>
            {% endif %}
            {% if saved_addresses %}
              <a class="btn btn-secondary" href="{% url 'select-from-saved-addresses' %}">Select from saved addresses</a>
            {% endif %}


        </div>



        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          {% include "order/order_contents.html" %}

          <!-- Promo code -->
            <form class="card p-2">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
                <div class="input-group-append">
                  <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
                </div>
              </div>
            </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

order/templates/order/contact_form.html
{% extends "order/base.html" %}

{% load crispy_forms_tags %}
{% block content %}
  <!--Main layout-->
  <main>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
      {% endif %}

      <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="">
                <legend class="border-bottom mb-4">Contact Us</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Send Email</button>
            </div>
        </form>


    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

order/templates/order/home-page.html
{% extends "order/base.html" %}


{% block content %}
  <!--Main layout-->
  <main>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
      {% endif %}

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'item-list' %}">Products
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio-list' %}">Portfolios</a>
            </li>
          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          {% for item in items %}
            <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                  alt="">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  {% if item.discount_price %}
                    <strong>{{ item.discount_price }}</strong>
                  {% else %}
                    <strong>{{ item.price }}</strong>
                  {% endif %}
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}

        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          <li class="page-item active">
            <a class="page-link" href="#">1
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">5</a>
          </li>

          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

order/templates/order/item_form.html
{% extends "order/base.html" %}

{% load crispy_forms_tags %}
{% block content %}
  <!--Main layout-->
  <main>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
      {% endif %}

      <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="">
                <legend class="border-bottom mb-4">Portfolio</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Create</button>
            </div>
        </form>


    </div>
  </main>
  <!--Main layout-->
{% endblock content %}

order/templates/order/order_contents.html
<!-- Cart -->
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.orderitem_set.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">{{ order_item.item.title }}</h6>
                <small class="text-muted">{{ order_item.item.description }}</small>
              </div>
              <span class="text-muted">${{ order_item.item.price }}</span>
            </li>
        {% endfor %}
        {% if coupon %}
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ coupon.code }}</small>
              </div>
              <span class="text-success">-${{ coupon.discount }}</span>
            </li>
        {% endif %}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total</span>
              <strong>${{ order.get_total_price }}</strong>
            </li>
    </ul>
<!-- Cart -->

order/templates/order/product-page.html
{% extends "order/base.html" %}


{% block content %}

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="{{ item.get_absolute_url }}">
                <span class="badge purple mr-1">{{ item.get_category_display }}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              {% if item.discount_price %}
                <span class="mr-1">
                  <del>${{ item.price }}</del>
                </span>
                <span>${{ item.discount_price }}</span>
              {% else %}
                <span>${{ item.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ item.description }}.</p>

              <!-- Default input -->

              <a class="btn btn-primary btn-md my-0 p" href="{{ item.get_add_to_cart_url }}">Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>

              <a class="btn btn-danger btn-md my-0 p" href="{{ item.get_remove_from_cart_url }}">Remove from cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>


          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}